language: python
python:
  - "2.7"
before_install:
  - "curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -"
  - 'sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"'
  - "sudo apt-get update"
  - "yes n | sudo apt-get install riak"
  - "sudo service riak start"
  - "wget http://leveldb.googlecode.com/files/leveldb-1.14.0.tar.gz"
  - "tar xvf leveldb-1*"
  - "cd leveldb*"
  - "make"
  - "sudo cp --preserve=links libleveldb.* /usr/local/lib"
  - "sudo cp -r include/leveldb /usr/local/include/"
  - "sudo ldconfig"
  - "cd .."
  - "mkdir -p dbs"
install:
  - pip install -r requirements.txt --use-mirrors
script: "python -m unittest discover"
